<?php
/**
 * Talkable SocialReferrals for Magento
 *
 * @package     Talkable_SocialReferrals
 * @author      Talkable (http://www.talkable.com/)
 * @copyright   Copyright (c) 2015 Talkable (http://www.talkable.com/)
 * @license     MIT
 */
?>

<?php $_helper = $this->helper("socialreferrals") ?>

<!-- Begin Talkable integration code -->

<?php if ($_helper->getSiteId() == ""): ?>
    <!-- Talkable Site ID is blank, check your Talkable extension settings -->
    <script type="text/javascript" src="//d2jjzw81hqbuqv.cloudfront.net/integration/talkable-2.2.min.js"></script>
<?php else: ?>
    <script type="text/javascript">
    //<![CDATA[
      var _talkableq = _talkableq || [];
      _talkableq.push(["init", {
        site_id: "<?php echo $_helper->getSiteId() ?>"
      }]);

      _talkableq.push(["authenticate_customer", <?php echo Mage::helper("core")->jsonEncode($_helper->getCustomerData()) ?>]);
    //]]>
    </script>
    <script type="text/javascript" src="//d2jjzw81hqbuqv.cloudfront.net/integration/clients/<?php echo $_helper->getSiteId() ?>.min.js"></script>
<?php endif ?>

<!-- End Talkable integration code -->
