<?php
/**
 * Talkable SocialReferrals for Magento
 *
 * @package     Talkable_SocialReferrals
 * @author      Talkable (http://www.talkable.com/)
 * @copyright   Copyright (c) 2015 Talkable (http://www.talkable.com/)
 * @license     MIT
 */
?>

<?php $_helper = $this->helper("socialreferrals") ?>

<?php if ($_helper->isPurchaseEnabled()): ?>
    <!-- Begin Talkable integration code -->

    <?php if ($_helper->getSiteId() == ""): ?>
        <!-- Talkable Site ID is blank, check your Talkable extension settings -->
    <?php else: ?>
        <?php if ($_order = $this->getCheckoutOrder()): ?>
            <script type="text/javascript">
            //<![CDATA[
              var _talkableq = _talkableq || [];
              _talkableq.push(["init", {
                site_id: "<?php echo $_helper->getSiteId() ?>",
                server: "https://www.talkable.com"
              }]);

              <?php $_event_data = $_helper->getPurchaseData($_order) ?>
              <?php $_event_data["responsive"] = true ?>
              <?php $_event_data["traffic_source"] = "Post-checkout" ?>
              <?php $_event_data["campaign_tags"] = $_helper->getPurchaseCampaignTags() ?>

              _talkableq.push(["register_purchase", <?php echo Mage::helper("core")->jsonEncode($_event_data) ?>]);
            //]]>
            </script>
            <script type="text/javascript" src="//d2jjzw81hqbuqv.cloudfront.net/integration/talkable-1.0.min.js"></script>
        <?php else: ?>
            <!-- Order could not be found -->
        <?php endif ?>
    <?php endif ?>

    <!-- End Talkable integration code -->
<?php endif ?>
