<?php
/**
 * Talkable SocialReferrals for Magento
 *
 * @package     Talkable_SocialReferrals
 * @author      Talkable (http://www.talkable.com/)
 * @copyright   Copyright (c) 2015 Talkable (http://www.talkable.com/)
 * @license     MIT
 */
?>

<?php $_helper = $this->helper("socialreferrals") ?>

<?php if ($_helper->isAffiliateEnabled()): ?>
    <!-- Begin Talkable integration code -->

    <?php if (empty($_helper->getSiteId())): ?>
        <!-- Talkable Site ID is blank, check your Talkable extension settings -->
    <?php else: ?>
        <div id="talkable-container"></div>
        <script type="text/javascript">
        //<![CDATA[
          var _curebitq = _curebitq || [];
          _curebitq.push(["init", {
            site_id: "<?php echo $_helper->getSiteId() ?>",
            server: "https://www.talkable.com"
          }]);

          <?php $_event_data = array_merge($_helper->getAffiliateData(), $_helper->getAffiliateIframeOptions()) ?>
          <?php $_event_data["campaign_tags"] = $_helper->getAffiliateCampaignTags() ?>

          _curebitq.push(["register_affiliate", <?php echo Mage::helper("core")->jsonEncode($_event_data) ?>]);
        //]]>
        </script>
        <script type="text/javascript" src="//d2jjzw81hqbuqv.cloudfront.net/integration/curebit-1.0.min.js"></script>
    <?php endif ?>

    <!-- End Talkable integration code -->
<?php endif ?>
